on: [push, pull_request]
name: Build
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:

  test:
    name: Build Desktop
    runs-on: ${{matrix.os.fullname}}
    env:
      OSU_EXECUTION_MODE: ${{matrix.threadingMode}}
    strategy:
       fail-fast: false
       matrix:
          os:
            - { prettyname: Windows, fullname: windows-latest }
            - { prettyname: macOS, fullname: macos-latest }
            - { prettyname: Linux, fullname: ubuntu-latest }
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Compile
        run: dotnet build -c Release -warnaserror osu.Desktop.slnf

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with: 
          # Artifact name
          name: osu.Desktop-${{matrix.os.fullname}} # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ./osu.Desktop
    

  build-only-android:
    name: Build only (Android)
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 11

      - name: Install .NET 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install .NET workloads
        run: dotnet workload install maui-android

      - name: Compile
        run: dotnet build -c Release osu.Android.slnf

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with: 
          # Artifact name
          name: osu-Android # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ./osu.Android

  build-only-ios:
    name: Build only (iOS)
    # `macos-13` is required, because the newest Microsoft.iOS.Sdk versions require Xcode 14.3.
    # TODO: can be changed to `macos-latest` once `macos-13` becomes latest (currently in beta: https://github.com/actions/runner-images/tree/main#available-images)
    runs-on: macos-13
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install .NET Workloads
        run: dotnet workload install maui-ios

      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer

      - name: Build
        run: dotnet build -c Release osu.iOS
  
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1  
        with: 
          # Artifact name
          name: osu.iOS # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ./osu.iOS
